version: '3.8'

services:
  db:
    image: postgres:17.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./src/database/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=veritasshield
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  veritas-shield:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/veritasshield
      - BKEY=sugmadik
      - BSALT=ligmaballs
      - BPERSON=deeznuts
      - API_SECRET=J3qwg-Qzy0qRVe7ZSy4v9MYGybsun9YQF1gmSn7ngBA
      - API_ID=AK7vuotWp153OWm4yrUVjQ
      - PDF_URL=http://http://20.2.138.242:8000/
    volumes:
      - ./src:/app/
    restart: always
volumes:
  postgres_data: